env:
  global:
    - secure: IOjW2Ulcquh3EH2o3k3uHF2BDQvuzIfCiPKo7JjHSVJsFFqkNUZkf5qPD8twiS0s6ECE2zS1Drw56sJN/MVmDD3UYCc7hMNj7xQk6SzM2UWSfbGjk4E8oqM31vkF2uQumpGHyag3L1eNRewzobUtXlcrYFMuYk8I5O6XjjH01OaL7Eh5xd+NSuvbNBOEwebk8qDdHp9QGClS2U7CfILSEdL1pUuNFjO5At8d5EZ2KdloRUTmEBeNE86O0Q35g69J84B70U8xNUscS24Ira68g+xTJtZ/IMFHGar7wyzR0kSeoMEEZYxtdfGt/oaZFwFS17NeQ/jKhS46F7OIMxoypP7+ZweWWSf67VP4vyU/wKi8JKvVGwx6GjgKF96PjGmiewduE85ySfLdXKWNSSiUD/8Qi3xWUqFI+bMBj0spRd+9sTZTL9i5mEOL+YaE2L3EPgICjGUvT/z2zOENDk8l7CKj9L2p9SzzuI2Hxs+ONMAERs5UQXNcXsi6DTrkoavC8XSXHlLx2x/1XzSBVH5bhMcn8n+RLtLYIZuIMo1XTPFIOLs+h37dvB9a6GEmWcotlAoJnonchUXtpULo2miRvrSCNOGf0V+gmvg6U44nhPFKkxg7ViKS9xlwDxYM/3RqBW7ab752UfLMzj4zMtIVw/5yuZwyOM1kn2pJrLuzVzU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
