env:
  global:
    - secure: M4WDpuOM2Fx91sabsbBmq3gd2H2z1yTDO0k5JQ6Cpa4LE6eFRvlVq8LcAdQpLSI8NEtxj51HPtF6QJHxqPXSso/+o0FPmtw+3MjUP+JxZyN51pEeJVMQ9bTJenW/Rg01keFAAhjwg6AXbkwqhWZy0Vu/PWI0AOL6Ixq7o3FBr4lR8MaFWC1vEPDrMN10/tDSkEmVCIAP5TyZnD2GZM0fpDQQR1xhk8PqgvjjuOzd7zvuFPXfPMRkXeOH6kQPzleCzWsGu+/D765Uo5Su7RQyLHAyQybDpBgLCpbh2OzWnEQqkx1exOj48p4ILRzhVMcUSm2NITBrDIJo2XMKdfHGn5Xlsw6YYs+W3p9xqGbiLLmRRn/onNZ4YKxM9LJYnr3T46XEmMwuoXmhntEzF4e2+MPaLAzZlgY0gFGP0fLdH8vlkuG+sI3o5HcyoTx27+LwM21joo4434IRb6lwyt5XTLVzS9hmL38Cj2xglTEh4+OpCBt3uWKZV+Dbyb0tDKrgyiFwVgR3DhCP5vwOT+aXTDvE0WDVxTe65F+xP5F+m2pukVTVn//UQlB3nKb/X2DIQX+ZwvJr1VMU4qPNJ9h0a/SSuUl7AZsVegHr6p/+1k3ArCAelkYHSfGA39YYHje9W6EEw4zRRDpM5UEPIv17mwR+Nz8rxVwTQr5HBVoVG/I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
