env:
  global:
    - secure: E/Hey88rM/h3Ki7pCpHJWv9wuCE4ee+H2AGB7CPDRj3T6Hz63AgG+Wq0TzN0CzBCP7PeE4EPT79bEzTjN8BXzl0LdzcsuV1AeIXvcqLxTQfnhxmZCUNEmQECVEQKDO4z//28yYzavVvwi6eoNsAgdnRi/X94Svp4NeC+lx8J7AABSWNxP9PzuUQTYkzvOl4m4i5uNNPgjCu0H/M1klQ5m+yjkZBCpz1lYiISy86ovkXVEC0Jj3PvZsoov4+IUh3jH7bs/dclItcGqh34EKStabkG99TQORCw9ny4joTWUT7EA7sEywyC3+GUu7dEJFGo1GNQ3RI08wDCoRODyi/RJkmXbGFWsckUPEpEKZFK7zOXPwNu1lV75kFxsaeepMsNdcfGmt/v652FMcj/6/2aLafJJYnU+GSzgVzYlAhG0V0A7Nc7zrwf0yp6Yd6pbZhQZr9BEf/xM2QwwqYpHeyU65Tq4+3Nf9TKDChJQCZtu9v8oarc5dFkEjeYBC7VlKZjqvPIo1edHRQlh2jlGh5BdCqEk7TWHhGrvosh3YvqjYu68tU7TKsAhBwfT571jEsDKqH7Ba+pdD9Fl/AjQtThDVH8XFXAAXuVog/N0qG8BYlhKPcRLxq9SumsxeOQPkymJTBCkD1Lsi2/esWRHhRRFXheIzl6qglFBlZA8OrJ53M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
