env:
  global:
    - secure: iXeL8kp/F0LHbROOaVB9mj9jKnpU+8yfSiNIvD6URgRNqHJEe6JRQz/fe+rQbHCxIjMECD5iwBJd9rl/YzlDUN4eWn9mNsvXglVxD/tBgAilDDuK5Lm0b3bXtoHtOf8YTqePpEr01p1qIGL6thqX692Eq+UBJ90uBLA0TYdTqPPPrnMZJn2z/6n3kSuvV6H0+7pwDhjTRaGZ+tww+R7WNm/ax0d0/10Cm6U7XjQ+7bm5lFCk0pUU90OglOa48YYUgQFMZhXIYYtVWbrjzcfNl52Je8DZTGMpEnjvkrdPakNQi6Y/+8uLEj0rl/KKMWmTqzKDHIxEiuoW7/oMZhlwFbl7AYAPovR0Er38Wu4TRj8CufICwAu5fkP/8QtYNNao/CVReKEB2plJh7s8P7VMU+j0eYEBKVTor7FOdGCPDwZIBE1KLlhlR594GSRGm+jmv/5yOvX2NTtJPnkmh+1kysmbQwz+SPUWmHB38QEnZzxw8hD5LOZtHMaIa8EJvjtb993AtLycf2pvaGGMuj9sSMAmDStDld9N0soOM0TVSFaZR0apv8hXmOgJxe5pVkkeHdBAJT8iwnWOC3yFMXTkSJQbUd09MZByLDOjEisI+6oWV8qL1LhokTmektxWaS1xyHzT44pWlM4DL8y/B5UuWcvY/iQrBy4ACGCNpf7Qdl4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
