env:
  global:
    - secure: EYqY7ZH8bcrJgOeK9O04uodE6SAib+oRNLvd+OJ7XT9BLNgF7HQoH6V6K2cJAcC54toDaOxiiv9RXQvxuYRuQu0cKL9AGAcPzH10D5SbFDcL05wXEkMsCt8Rc849MeXMN/e4Ddjgtddv8FsCillNUZ9FmwSEIaOwgfaQTvLJxyvmtZCnHrhE3IoVj4GWepGq2sdrAGbL1nmyaWjU+2frdbwjsxsYWE8WOgI0VjnRBRvVw8tMhOjQlo6B232PyepYp6snVP/eBmkGKt3gm+o0+xFjCgjO9+S5+CuoF6xeVLMiRmWOO4Y0hblFmY3M8+M9mZBb9mgs/9OSgQr2pBgIoLkAd9hDBXLXjYGJCBqah2pUNC8QJyNEy5q2+1aCZ7ALwo0cWfveLgyvLF5+5SJDR8uJOoznMF0qYSuTL1IoMW7VXas6ZOedgbzZix7SenO4xCPLRhX1f4pgWOudfpzaHxrdSdYjzZdFIFBXaU6x2Rv9J0nwGIKJOS91WnO9mGYCO/HnvmER08hYOJgMGOWap8Vbury+yZYYLdLmgh/EF2/5w4fbDVW8cvjX/si4Vf4COAUwssZVRyXy3bi5T713HcV1PrH5GWZCcjXn3nUGRnQwWzoiK/TTxOuJxzv/E6HEnSW1iQPSLGJW1IU9AsJja0uBiLAl02l2NP3v5n1JYmg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
