env:
  global:
    - secure: nnmYfJjeLb34usiYeB0fu/EDV1n9YC2ZAK+a1paRmE6bpENGV+7jR9nKKhciHMUb1wxwZluw4DgXJwQN0xLJkNZXaiWfxgurVy3dlR72i+pHSMxsVCXp98Y+cS8Gvpen4eE+G9ep+PsOeeeeFMsmMnC/W3SaPLXnqBu7lJCaIxo0J/zL1SsReFd0rPKedNLtfJoL9sC9AlJ3rm3X2588PniEBfE384QxKDW6AkW3nRhFSgPSID7vj/s0a6SHfN+9POwC3IfLoHeBRWQxt5Sq8bVsr7rR/BHvCoX6hSDAAvTGo4Nc9HxuBqNzO4oAA0YnbKrtniTrCB8M9M+ElZpArFr+Iocnj/0iCWzaHVfQaWyZYxV00CnUNMrg6PRlN0N9P1++QWouZKuYCu7683CRp1qTCNnMQSefj6TkoywLtDMM3+9G9Mxnzs24aTDlTUp0pNxDcu14wX7DtwW6U16+dVvX6VxEt1jyQ/17eJkWF/B2GQfDhKFl2ELW2LJiZ/JYm0zpDwvbS34U+vXccyAC1RLKuTzr0KbCYY7xQTsRaL+tsj+HpRykzeDr1OLOgsNuZ0Z7VwqLCazLPzewowNSj5BfCslYt9LE7JlRM8VMao6NXvuljU8kazt2St5x9zxT9IwiVPxqw8Qv3b6n5ZLT2/NiLBVhk6LuWBnUd+m1TdE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/WaLLy3K_Blacklist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
